title = "Kubernetes"
baseURL = "https://singhankit.com"
languageCode = "en-us"
theme = "gohugo-theme-ananke-master"
[taxonomies]
  tag = "tags" #singular = plural taxonomies
  category = "categories"
  mood = "moods"
  
[params]
  favicon = ""
# site_logo = "img/logo.svg"
  description = "Blog Post"
  facebook = "https://facebook.com"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/Kubernetes-logo.jpg"
  body_classes = "avenir bg-near-blue"
